title: Pradeep Kalluri
description: Data Engineer | Cloud Platforms | DataOps
theme: minima

author:
  name: Pradeep Kalluri
  email: kalluripradeep99@gmail.com

social_links:
  github: kalluripradeep
  linkedin: pradeepkalluri

header_pages:
  - about.md
  - experience.md
  - projects.md
  - contact.md