title: Pradeep Kalluri
description: Data Engineer | Cloud Platforms | DataOps
theme: minima
author: Pradeep Kalluri
email: kalluripradeep99@gmail.com

baseurl: ""
url: "https://kalluripradeep.github.io"

social_links:
  github: kalluripradeep
  linkedin: pradeepkalluri

header_pages:
  - about.md
  - experience.md
  - projects.md
  - contact.md

minima:
  skin: classic
  social_links:
    github: kalluripradeep
    linkedin: pradeepkalluri

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md