baseURL: "https://kalluripradeep.github.io/"
languageCode: "en-us"
title: "Pradeep Kalluri"
theme: "ananke"

params:
  author: "Pradeep Kalluri"
  description: "Data Engineer specializing in cloud data platforms, ELT pipelines, and DataOps"
  favicon: ""
  site_logo: ""
  background_color_class: "bg-black"
  recent_copy: "Recent Work"
  body_classes: "sans-serif"
  post_content_classes: "center"
  featured_image: ""
  
  social:
    - name: github
      url: https://github.com/kalluripradeep
    - name: linkedin  
      url: https://www.linkedin.com/in/pradeepkalluri
    - name: email
      url: mailto:Pradeepkalluri143@gmail.com

menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Experience
      url: /experience/
      weight: 2
    - name: Projects
      url: /projects/
      weight: 3
    - name: Contact
      url: /contact/
      weight: 4